wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.15
    start_time: 1671125038.557427
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      3:
      - 23
      4: 3.7.15
      5: 0.13.7
      6: 4.24.0
      8:
      - 2
      - 5
