wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.15
    start_time: 1671103491.452221
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 23
      4: 3.7.15
      5: 0.13.6
      6: 4.25.1
      8:
      - 2
      - 5
